### ISSUE TITLE
Q: Delay between valves

### ISSUE THREAD

**Issue by gvdhoven** [petergridge/irrigation_component_V3#3]
Wonderfull work! I have 2 questions:
1) Is it possible to have one zone, with 2 valves but delay in between?

Rationale: I have my lawn split into 2 valves due to not enough water pressure. I want that when i say: "Water the lawn" that first valve 1 goes for 5 minutes, then valve 2 for 5 minutes, then valve 1 for 15 minutes and then valve 2 for 15 minutes. is that possible with your component:

2) Can you start then this "irrigation" sequence by a HA switch?

Rationale: So i can add it to Google Assistant

**Comment by petergridge** [comment]
Hi,  I would recommend v4 now,  I have new version being released in the next couple of days once I have completed testing.  The program or schedule is exposed as an HA switch so it can easily be turned on or off.  The zones are children of the program and run sequentially by default.  I can provide example yaml if you have problems setting it up.

**Comment by petergridge** [comment]
Hi,

Version 4 has been updated and is much more stable, but please let me know if you have any issues it has been a significant rewrite of version 3:
https://github.com/petergridge/irrigation_component_v4

A custom card is available it saves you a lot of lovelace configuration:
https://github.com/petergridge/irrigation_card

You may also find the discussion on the HA community useful:
https://community.home-assistant.io/t/irrigation-custom-component-with-custom-card/124370

This config is a very basic setup that will run two zones sequentially at a given time at the defined frequency. Once you add it you will see a switch.afternoon available. There are many more configuration options available have a read of the documentation. 
``` yaml
    sensor:
      - platform: time_date
        display_options:
          - 'time'
          - 'date'

    input_datetime:
      irrigation_afternoon_start_time:
        name: Afternoon Start Time
        has_date: false
        has_time: true

    sensor:
      - platform: time_date
        display_options:
          - 'time'
          - 'date'
      - platform: openweathermaphistory
        name: 'rainfactor'
        api_key: !secret openweatherapi

    switch:
      - platform: irrigationprogram
        switches: 
          afternoon:
            start_time: input_datetime.irrigation_afternoon_start_time
            run_freq: input_select.irrigation_freq
            zones:
              - zone: switch.'switch exposed by your controller'
                name: Lawn 1
                water: input_number.irrigation_lawn_run
                icon: mdi:grass
             - zone: switch.'switch exposed by your controller'
                name: Lawn 2
                water: input_number.irrigation_lawn_run
                icon: mdi:grass

    input_number:
      irrigation_lawn_water:
        name: water
        min: 1
        max: 30
        step: 1
        icon: mdi:water

    input_select:
      irrigation_freq:
        name: Frequency
        options:
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
          - "7"
          - "['Wed','Sat']"
          - "['Sun','Thu']"
          - "['Mon','Fri']"
          - "['Tue','Sat']"
          - "['Sun','Wed']"
          - "['Mon','Thu']"
          - "['Tue','Fri']"
          - "['Mon','Wed','Fri']"
          - "['Mon','Tue','Wed','Thu','Fri','Sat','Sun']"
```
